/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalhoRPG;

import javax.swing.JOptionPane;

/**
 *
 * @author sesia
 */
public class TelaLuta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLuta.class.getName());

    private Personagem jogador;
    //Inimigo tempo
    Personagem inimigo = new Inimigo("Inimigo", 50, 20, 8, 4);

    private int bonusForcaTurno = 0;
    private int bonusAgilidadeTurno = 0;

    /**
     * Creates new form TelaLuta
     */
    public TelaLuta() {
        initComponents();
    }
    //Criado para armazenar o personagem escolhido na outra tela
    public TelaLuta(Personagem jogador) {
        initComponents();
        this.jogador = jogador;
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemLuta.jpg"))); 
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagemLuta.jpg"))); 
        textoTela.append("Para inciar a batalha, clique no botão INICIAR\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        barraManaJogador = new javax.swing.JProgressBar();
        labelManaJogador = new javax.swing.JLabel();
        labelVidaJogador = new javax.swing.JLabel();
        barraVidaJogador = new javax.swing.JProgressBar();
        labelVidaInimigo = new javax.swing.JLabel();
        barraVidaInimigo = new javax.swing.JProgressBar();
        labelManaInimigo = new javax.swing.JLabel();
        barraManaInimigo = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        btnAtacar = new javax.swing.JButton();
        btnHabilidade = new javax.swing.JButton();
        btnItem = new javax.swing.JButton();
        btnFugir = new javax.swing.JButton();
        btnRolarDados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoTela = new javax.swing.JTextArea();
        btnIniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        labelManaJogador.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        labelManaJogador.setText("MANA");

        labelVidaJogador.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        labelVidaJogador.setText("VIDA");

        labelVidaInimigo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        labelVidaInimigo.setText("VIDA INIMIGO");

        labelManaInimigo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        labelManaInimigo.setText("MANA INIMIGO");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monstroImagemm.png"))); // NOI18N

        btnAtacar.setText("Atacar");
        btnAtacar.addActionListener(this::btnAtacarActionPerformed);

        btnHabilidade.setText("Habilidade");
        btnHabilidade.addActionListener(this::btnHabilidadeActionPerformed);

        btnItem.setText("Item");
        btnItem.addActionListener(this::btnItemActionPerformed);

        btnFugir.setText("Fugir");
        btnFugir.addActionListener(this::btnFugirActionPerformed);

        btnRolarDados.setText("Rolar Dados");
        btnRolarDados.addActionListener(this::btnRolarDadosActionPerformed);

        textoTela.setColumns(20);
        textoTela.setRows(5);
        jScrollPane1.setViewportView(textoTela);

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        jLabel4.setText("X");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtacar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHabilidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(btnItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFugir)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelManaJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barraManaJogador, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(barraVidaJogador, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(labelVidaJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelManaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barraVidaInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(barraManaInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(labelVidaInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIniciar)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRolarDados)
                        .addGap(207, 207, 207))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelVidaJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(barraVidaJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelManaJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barraManaJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelVidaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(barraVidaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelManaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraManaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtacar)
                    .addComponent(btnHabilidade)
                    .addComponent(btnItem)
                    .addComponent(btnFugir))
                .addGap(18, 18, 18)
                .addComponent(btnRolarDados)
                .addGap(57, 57, 57))
        );

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilidadeActionPerformed
           // Botao para o jogador usar a habilidade do seu perosnagem
        String habilidadeJogador = jogador.usarHabilidade(inimigo);
        textoTela.append(habilidadeJogador + "\n");

        // Ataque do inimigo 
        //RN09: O inimigo sempre contra-ataca no turno seguinte, caso ainda esteja vivo
        //Verifica se o inimigo esta vivo ainda
        if (inimigo.estaVivo()) {
            String habilidadeInimigo = inimigo.atacar(jogador);
             textoTela.append(" TURNO INIMIGO -------\n");
            textoTela.append(habilidadeInimigo + "\n");
        }

        atualizarBarras();
        fimBatalha();
    }//GEN-LAST:event_btnHabilidadeActionPerformed

    private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemActionPerformed
       //Vai escolher o item ou de vida ou de mana
        Item item = GerarItem.gerarItensAtributos();

        //Jogador vai poder usar
        String usadoItem = jogador.usarItem(item);

        textoTela.append(usadoItem + "\n");
        atualizarBarras();
    }//GEN-LAST:event_btnItemActionPerformed

    private void btnFugirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFugirActionPerformed
        // Jogador pode tentar fugir
        String falhou = jogador.fugir(inimigo);
        textoTela.append(falhou + "\n");

        // Se na chance, der errado, o inimigo vai atacar
        //Para verificar se o ataque falhou e o inimgo pode atacar
        //falhou.contains verifica se o ataque do jogador falhou
        //Se falhou o inimigo ataca e mostra o log do ataque inimigo na tela
        if (falhou.contains("falhou")) {
            String falhouInimigo = inimigo.atacar(jogador);
            textoTela.append(falhouInimigo + "\n");

            atualizarBarras();
            fimBatalha();
        } else { JOptionPane.showMessageDialog(this, "Você escapou");
            this.dispose();
        }
    }//GEN-LAST:event_btnFugirActionPerformed

    private void atualizarBarras() {
        //Atualizar barra de vida do jogador
        barraVidaJogador.setValue(jogador.getVida());
        //Atualizar barra de mana do jogador
        barraManaJogador.setValue(jogador.getMana());
        
         //Atualizar barra de vida do inimigo
        barraVidaInimigo.setValue(inimigo.getVida());
        //Atualizar barra de mana do inimigo
        barraManaInimigo.setValue(inimigo.getMana());
    }
    
    
    private void btnRolarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolarDadosActionPerformed
    bonusForcaTurno = Dados.rolar(1, 6);
    bonusAgilidadeTurno = Dados.rolar(1, 4);

    
    textoTela.append("Dados do turno: ");
    textoTela.append("Bônus de Força: + " + bonusForcaTurno);
    textoTela.append("Bônus de Agilidade: + " + bonusAgilidadeTurno);
    }//GEN-LAST:event_btnRolarDadosActionPerformed

    private void fimBatalha() {
        if (!jogador.estaVivo()) {
            JOptionPane.showMessageDialog(this, "Você perdeu a Batalha ");
            this.dispose();
        } 
        else if (!inimigo.estaVivo()) {
            JOptionPane.showMessageDialog(this, "Você derrotou o Inimigo");
            this.dispose();
        }
    }
    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        // TODO add your handling code here:
          // Jogador ataca
        String ataqueJogador = jogador.atacar(inimigo);
        textoTela.append(ataqueJogador + "\n");

        // Se o inimigo ainda estiver vivo, ele ataca
        if (inimigo.estaVivo()) {
            String ataqueInimigo = inimigo.atacar(jogador);
             textoTela.append(" TURNO INIMIGO -------\n");
            textoTela.append(ataqueInimigo + "\n");
        }

        atualizarBarras();
        fimBatalha();
        
    }//GEN-LAST:event_btnAtacarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        textoTela.append("Um Inimigo apareceu \n");
        textoTela.append("Gire o dado para começar o combate \n");
        atualizarBarras();
    }//GEN-LAST:event_btnIniciarActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraManaInimigo;
    private javax.swing.JProgressBar barraManaJogador;
    private javax.swing.JProgressBar barraVidaInimigo;
    private javax.swing.JProgressBar barraVidaJogador;
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnFugir;
    private javax.swing.JButton btnHabilidade;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnItem;
    private javax.swing.JButton btnRolarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelManaInimigo;
    private javax.swing.JLabel labelManaJogador;
    private javax.swing.JLabel labelVidaInimigo;
    private javax.swing.JLabel labelVidaJogador;
    private javax.swing.JTextArea textoTela;
    // End of variables declaration//GEN-END:variables
}
