/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetorev01;

import java.util.Arrays;//Importanto a classe arrays do pacote java.util

public class App {
    

    public static void main(String[] args) {
        //Array em java tem tamanho fixo
        //Criando um array de 5 itens, ele sempre terá 5 itens 
        //Não posso acrescentar mais ou retirar 
        int[] numeros;
        //Existem DUAS formas de declarar array
        //1. Usando o operador NEW
        numeros = new int[5];
        numeros[0] = 50;
        numeros[1] = 80;
        numeros[2] = 120;
        numeros[3] = 70;
        numeros[4] = 30;
        
        for (int i = 0; i < numeros.length; i++){
            System.out.println("numeros[i]");
        }
        
        //2. Passando os valores diretamente
        String[] nomes = {"Leo", "Robers", "Bruna"};
        for (int i = 0; i < nomes.length; i++){
            System.out.println("nomes[i]");
        }
        
        //Ele ordena os valores do array
        Arrays.sort(numeros);
        System.out.println("Array ordenado:");
        for (int i = 0; i < numeros.length; i++){
            System.out.println("numeros[i]");
        }
        
        
        Pessoa pessoa = new Pessoa ("Leo",30,70.00);
        pessoa.andar();
        
        Pessoa.falar(); //utilizando o Static 
        
        System.out.println("Programa executando..");

    }
    
}
